# Generated by Django 5.0.6 on 2024-05-09 18:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0004_alter_category_options_contact_owner"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="createde_date",
            new_name="created_date",
        ),
    ]
